pipeline{
    agent any
    tools {
        nodejs 'NodeJS_22'
    }
    stages {
        stage("Checar a Versão do NodeJS"){
            steps {
                script {
                    def nodeVersion = sh(script: 'node -v', returnStdout: true).trim()
                    echo "NodeJS version: ${nodeVersion}"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}