pipeline{
    agent any
    tools {
        nodejs 'NodeJS_22'
    }
    stages {
        stage("Checar a Versão do NodeJS"){
            steps {
                script {
                    def nodeVersion = sh(script: 'node -v', returnStdout: true).trim()
                    echo "NodeJS version: ${nodeVersion}"
                }
            }
        }
        stage("Checar a Versão do Yarn"){
            steps {
                script {
                    def yarnVersion = sh(script: 'yarn -v', returnStdout: true).trim()
                    echo "Yarn version: ${yarnVersion}"
                }
            }
        }

        stage("Instalar as Dependencias do projeto"){
            steps {
                script {
                    sh "cd /var/lib/jenkins/workspace/FrontendQRCodeGenerate/frontend && yarn install"
                }
            }
        }
        stage("Rodar o Build do projeto"){
            steps {
                script {
                    sh "cd /var/lib/jenkins/workspace/FrontendQRCodeGenerate/frontend && yarn build"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}