pipeline{
    agent any
    stages{
        stage("Navegação ate a Pasta do Projeto"){
            steps{
                sh "cd /var/lib/jenkins/workspace/BackendQRCodeGenerate/backend"
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}