pipeline{
    agent any
    stages{
        stage("Navegação ate a Pasta do Projeto"){
            steps{
                script {
                    sh "cd /var/lib/jenkins/workspace/BackendQRCodeGenerate/backend"
                }
            }
        }

        stage("Build Image Docker"){
            steps {
                script {
                    def imageName = "jandernery/qrcode-generate:v1"
                    def imageNameLatest = "jandernery/qrcode-generate:latest"

                    docker.build(imageName, '/var/lib/jenkins/workspace/BackendQRCodeGenerate/backend')
                    docker.build(imageNameLatest, '/var/lib/jenkins/workspace/BackendQRCodeGenerate/backend')
                }
            }
        }

        stage("Docker Push"){
            steps{
                script {
                    def imageName = 'jandernery/qrcode-generate:v1'
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        docker.image(imageName).push()
                    }
                }
            }
        }

        stage("Docker Run Application"){
            steps{
                script {
                    def imageNameLatest = "jandernery/qrcode-generate:latest"
                    
                    sh "docker rm -f ${imageNameLatest} || true" 

                    sh """
                        docker run -d \
                            -p 4545:4545 \
                            ${imageNameLatest}
                    """
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}